name: AirTrack CI Inspector

# Trigger this workflow when code is pushed to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  inspect-code:
    runs-on: ubuntu-latest # Use a standard Ubuntu Linux runner

    steps:
    # Step 1: Download our repository code
    - name: Download Code
      uses: actions/checkout@v4

    # Step 2: Setup the Go programming environment
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    # Step 3: Compile the code to catch any syntax errors
    - name: Test the Build
      run: go build main.go

    # Step 4: Print a success message if the build passes
    - name: Final Report
      run: echo "Pipeline Phase 1 Complete. Emitting repository dispatch to DevOps repository."

    # Step 5: Send a signal to the DevOps repo to start the Docker build
    - name: Trigger the DevOps Repository
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.MY_SECRET_PASSWORD }}
        repository: DilukshiWijayawardhana/air-global-baggage-tracker-devops
        event-type: start-docker-build